import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateASDReport = (child, result) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    const ethnicities = [
        { label: "White-European", value: 10 },
        { label: "South Asian", value: 8 },
        { label: "Asian", value: 1 },
        { label: "Middle Eastern", value: 5 },
        { label: "Black", value: 2 },
        { label: "Latino", value: 4 },
        { label: "Hispanic", value: 3 },
        { label: "Pasifika", value: 7 },
        { label: "Turkish", value: 9 },
        { label: "Others", value: 6 }
    ];

    const countries = [
        { label: "United States", value: 51 },
        { label: "United Kingdom", value: 50 },
        { label: "India", value: 18 },
        { label: "Australia", value: 3 },
        { label: "Canada", value: 10 },
        { label: "New Zealand", value: 34 },
        { label: "Sri Lanka", value: 6 },
        { label: "Egypt", value: 13 },
        { label: "Other Country", value: 0 }
    ];

    const formatDate = (dateString) => {
        return new Date(dateString).toLocaleDateString(undefined, {
            year: 'numeric', month: 'short', day: 'numeric',
            hour: '2-digit', minute: '2-digit'
        });
    };

    // Header
    doc.setFontSize(22);
    doc.setTextColor(79, 70, 229); // Primary color
    doc.text('ASD Prediction Report', pageWidth / 2, 20, { align: 'center' });
    
    doc.setDrawColor(226, 232, 240);
    doc.line(20, 25, pageWidth - 20, 25);
    
    // Child Information
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text('Child Information', 20, 35);
    
    const ethnicityLabel = ethnicities.find(e => e.value === Number(child.ethnicity))?.label || 'N/A';
    const countryLabel = countries.find(c => c.value === Number(child.country))?.label || 'N/A';

    const childInfo = [
        ['Name', child.name || 'Anonymous'],
        ['Age', `${child.age} Years`],
        ['Sex', child.sex === 1 ? 'Male' : 'Female'],
        ['Ethnicity', ethnicityLabel],
        ['Country', countryLabel]
    ];
    
    autoTable(doc, {
        startY: 40,
        head: [],
        body: childInfo,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 2 },
        columnStyles: { 0: { fontStyle: 'bold', width: 40 } }
    });
    
    // Assessment Results
    const resultY = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.text('Assessment Results', 20, resultY);
    
    const assessmentInfo = [
        ['Date', formatDate(result.date || new Date())],
        ['Assessment Type', result.features?.type || 'Assessment'],
        ['Result', result.prediction === 'Positive' ? 'High Risk' : 'Low Risk'],
        ['Probability', result.probability ? `${Math.round(result.probability * 100)}%` : 'N/A'],
        ['Behavioral Score', `${result.features?.behavioral_score || 0} / 10`]
    ];
    
    autoTable(doc, {
        startY: resultY + 5,
        head: [],
        body: assessmentInfo,
        theme: 'striped',
        styles: { fontSize: 10, cellPadding: 3 },
        columnStyles: { 0: { fontStyle: 'bold', width: 40 } }
    });
    
    // Clinical Concerns
    if (result.features?.clinical_history) {
        const clinicalY = doc.lastAutoTable.finalY + 15;
        doc.setFontSize(14);
        doc.text('Clinical Observations', 20, clinicalY);
        
        const clinicalHistory = Object.entries(result.features.clinical_history)
            .map(([key, value]) => [
                key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase()),
                value ? 'Yes' : 'No'
            ]);
            
        autoTable(doc, {
            startY: clinicalY + 5,
            head: [['Concern', 'Observation']],
            body: clinicalHistory,
            theme: 'grid',
            headStyles: { fillColor: [79, 70, 229] },
            styles: { fontSize: 9 }
        });
    }
    
    // Footer
    const finalY = (doc.lastAutoTable?.finalY || resultY + 50) + 20;
    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.text('Disclaimer: This report is generated by an AI model and should not be considered a formal medical diagnosis.', 20, finalY);
    doc.text('Please consult with a qualified healthcare professional for a complete evaluation.', 20, finalY + 5);
    
    doc.save(`${(child.name || 'Child').replace(/\s+/g, '_')}_ASD_Report.pdf`);
};
